environment:
  base_version: '1.0.3'
  version_suffix: ''
version: $(base_version).{build}
image: Visual Studio 2019
configuration: Release
branches:
  only:
  - master
before_build:
    - ps: nuget restore .\YahooXL.sln
build:
  project: .\YahooXL.sln
  verbosity: minimal
after_build:
  - cmd: 7z a Package.zip %APPVEYOR_BUILD_FOLDER%\YahooXL\bin\Release\*.*
artifacts:
- path: Package.zip
  name: Package
