environment:
  base_version: '1.1.0'
  version_suffix: ''
version: $(base_version).{build}
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(base_version)$(version_suffix)'
  package_version: '$(base_version)$(version_suffix)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '$(base_version)$(version_suffix)'
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a YahooXL-packed.zip %APPVEYOR_BUILD_FOLDER%\YahooXL\bin\Release\*.*
artifacts:
- path: YahooXL-packed.zip
  name: YahooXL-packed
