environment:
  base_version: '1.0.0'
  version_suffix: '-alpha'
version: $(base_version).{build}
image: Visual Studio 2019
configuration: Release
branches:
  only:
  - master
before_build:
    - ps: nuget restore .\YahooXL.sln
build:
  project: .\YahooXL.sln
  verbosity: minimal
after_build:
  7z a myapp.zip \bin\Release\*.*
artifacts:
- path: myapp.zip
  name: MyApp
